Ratings intergration
ubuntu/app-center pull request #1371
Opened 2023-09-13 14:28 UTC by matthew-hagemann

Creating as a draft until I finish updating the tests, but probably best to start getting eyes on this now

- Created new provider `ratingsModelProvider` for getting rating of snap in the details_page.
- Created new provider `ratingsModelListProvider` for getting ratings of snaps in the search and explore pages.
- Created new service `ratingsService` that wraps the ratings client that can be found [here](https://github.com/matthew-hagemann/app_center_ratings_client.dart)

TODO:
- Add new tests
- Update Insufficient Ratings once designs are finalized
- Move ratings client to Canonical github org and update dependency

2023-09-14 14:20 UTC, d-loose commented on lib/src/detail/detail_page.dart
> +class SnapInfo {
Does this need to be upgraded to a class or can we leave it as a record type?

2023-09-14 14:22 UTC, d-loose commented on lib/src/detail/detail_page.dart
> +      data: (snapData) => ResponsiveLayoutBuilder(
`state` is `AsyncValue<void>`, so the argument of the closure doesn't need to be named
```suggestion
      data: (_) => ResponsiveLayoutBuilder(
```

2023-09-14 14:25 UTC, d-loose commented on lib/src/detail/detail_page.dart
> +  });
It'd be great to keep pure formatting changes out of PRs like this, since they can clutter the diff a bit :)

2023-09-14 14:26 UTC, d-loose commented on lib/src/explore/explore_page.dart
>          ?.where(
Any particular reason you removed those comments?

2023-09-14 14:28 UTC, d-loose commented on lib/src/widgets/snap_card.dart
> +  SnapCard({
Should stay `const` (prefer_const_constructors_in_immutables)

2023-09-14 14:28 UTC, d-loose commented on lib/src/widgets/snap_card.dart
> +  SnapImageCard({super.key, required this.snap, this.onTap});
Should stay `const` (prefer_const_constructors_in_immutables)

2023-09-14 14:29 UTC, d-loose commented on lib/src/widgets/snap_card.dart
> +              ),
Unrelated style change

2023-09-14 14:29 UTC, d-loose commented on lib/src/widgets/snap_card.dart
> +  _SnapCardBody({required this.snap, this.maxlines = 2});
Should stay `const` (prefer_const_constructors_in_immutables)

2023-09-14 14:32 UTC, d-loose commented on lib/src/widgets/snap_card.dart
> +                ' | ${rating?.totalVotes} ${l10n.snapRatingsVotes}',
It'd be better to use an l10n string that accepts a placeholder argument here, since the placement of the translated word(s) and the number of votes might not be the same in every language. Also makes it easier to test.

2023-09-14 14:33 UTC, d-loose commented on test/detail_page_test.dart
> +    id: "r4LxMVp7zWramXsJQAKdamxy6TAWlaDD");
Could we get a trailing comma? :)

2023-09-14 14:38 UTC, d-loose commented on test/snap_card_test.dart
> +    expect(find.text(' | 123 votes'), findsOneWidget);
Those tests should use localizations strings. You can access them via the l10n extension on the `WidgetTester` from the test utils

2023-09-14 14:39 UTC, matthew-hagemann commented on lib/src/detail/detail_page.dart
> +class SnapInfo {
I was getting the error "'SnapInfo' isn't a function.
Try correcting the name to match an existing function, or define a method or function named 'SnapInfo'." when trying to return SnapInfo from the _SnapInfos build class method. Not sure if there is a better way to solve this than turning it into a class?

2023-09-14 14:41 UTC, d-loose requested changes
Could we also get that lib/ratings.dart we talked about and `import '/ratings.dart'` instead?

Hope the comments aren't too blunt - great work overall, thanks a lot!

2023-09-15 07:27 UTC, matthew-hagemann commented
Not quite sure what to make of CI failures.

Analyze wants me to swap to relative imports in lib/src, but I believe we want to avoid doing that? Is there somthing we want to update in `analysis_options.yaml`?
Mocks are freshly updated, not sure why that failed?

2023-09-15 08:36 UTC, d-loose approved these changes
Cleaned up imports and regenerated mocks. Also removed the loading spinner from the card, we can check back later with Ana to see if it's necessary, but I think it doesn't look great :)

LGTM :+1:

2023-09-15 08:39 UTC, merged