feat: snapd error handling
ubuntu/app-center pull request #1396
Opened 2023-09-20 15:30 UTC by d-loose

UDENG-1363
UDENG-1422
Close #1366
Ref #1394 

![image](https://github.com/ubuntu/app-center/assets/113362648/f648f6f1-74a2-480c-87f2-c11cdaf1fee7)
(This state isn't reachable in practice, since we don't show the update button unless there is an update available)

* Adds a rudimentary error dialog widget
* Adds error streams to `SnapModel` and `UpdateModel`
* Logs snapd exceptions caught in the `SnapdModel` and `UpdateModel`
* Shows an error dialog on the `SnapPage` and `ManagePage` when errors are caught in the underlying models

2023-09-21 09:31 UTC, tim-hm requested changes
I'm getting an error when trying to install a snap. Are you experiencing the same?

```
flutter: ERROR snap: Caught exception for snap "gnome-mahjongg"
	SnapdException: SnapdException(kind: login-required, message: access denied)
```

Otherwise a few comments scattered throughout.

2023-09-21 09:31 UTC, tim-hm commented on lib/src/snapd/updates_model.dart
> +final log = Logger('snap');
There is also a logger in snap_model.dart. I don't know what the convention is so ignore me if this doesn't apply, but would you normally have a single logger at the package / folder level?

2023-09-21 09:31 UTC, tim-hm commented on lib/snapd.dart
> +export 'src/snapd/updates_model.dart' hide log;
Ref comment elsewhere about the log instance in snap_model.dart, you might want to hide it here as well (or consolidate to 1 logger instance)

2023-09-21 09:50 UTC, d-loose commented
> I'm getting an error when trying to install a snap. Are you experiencing the same?
> 
> ```
> flutter: ERROR snap: Caught exception for snap "gnome-mahjongg"
> 	SnapdException: SnapdException(kind: login-required, message: access denied)
> ```
> 
> Otherwise a few comments scattered throughout.

No, I don't. Are you logged into snapd? If not, clicking 'install' should invoke polkit and ask for your password.

2023-09-21 09:53 UTC, d-loose commented on lib/src/widgets/dialogs.dart
> +import 'package:flutter/material.dart';
I'm anticipating adding additional dialog types (e.g. confirmation before removing an app). Should have left a comment, though :)

2023-09-21 09:57 UTC, d-loose commented on lib/src/snapd/updates_model.dart
> +final log = Logger('snap');
I was following the pattern used in ubuntu-desktop-provision, but I'm open to trying out a different approach, as this can potentially be a little error-prone if we forget to explicitly hide `log` from some exports

2023-09-21 10:51 UTC, tim-hm commented on lib/src/snapd/updates_model.dart
> +final log = Logger('snap');
You have more experience with this codebase so you tell me how you want to do it!

2023-09-21 10:57 UTC, tim-hm commented
Ah the error is caused because I'm using vscodes remote development to run the app so I never get the polkit prompt. Works as expected when I run directly from my desktop.

2023-09-21 12:32 UTC, d-loose commented on lib/src/manage/manage_page.dart
> +        title: e.kind ?? '',
I'm hardcoding those for now, since we'll address showing proper error messages in #1362

2023-09-21 12:39 UTC, d-loose commented on lib/src/snapd/updates_model.dart
> +final log = Logger('snap');
I've added a 'logger.dart' in lib/src/snapd, which can be imported within the directory, but is not listed in the exports in lib/snapd.dart. Will do the same for the other directories as we go.

2023-09-25 15:56 UTC, tim-hm approved these changes
Apologies I meant to say go ahead and merge when you're happy!

2023-09-25 16:03 UTC, merged