feat: Games tab overhaul
ubuntu/app-center pull request #1598
Opened 2024-02-12 17:55 UTC by ashuntu

Here's what the tab looks like right now as you scroll down it:

![Carousel and featured games](https://github.com/ubuntu/app-center/assets/101582426/0294967b-3986-410f-a3c9-743fcacc3d0c)
![All games](https://github.com/ubuntu/app-center/assets/101582426/5d2fec00-f938-4c80-b62f-c714091f0b9d)
![External resources and app bundles](https://github.com/ubuntu/app-center/assets/101582426/6c0d0a07-3882-4c34-abd1-9d749a403234)

Example app bundle page:

![image](https://github.com/ubuntu/app-center/assets/101582426/f3e4a237-73f7-4ede-82c8-953793bb56ea)

External resources page:

2024-02-15 12:41 UTC, michaldev commented
"develop your own game" should be in the "development" tab in my opinion. The "games" tab should be intended for players.

2024-02-20 10:17 UTC, d-loose commented on packages/app_center/lib/src/widgets/app_card.dart
> +    required AppLocalizations l10n,
Remove `l10n` argument and get it from the build context instead

2024-02-20 10:18 UTC, d-loose commented on packages/app_center/lib/src/widgets/app_card.dart
> +          child: Text(l10n.openInBrowser),
You can wrap the `Text` widget in a `Builder` to get a build context here

2024-02-20 10:20 UTC, d-loose commented on packages/app_center/lib/src/widgets/app_title.dart
> +  factory AppTitle.fromTool(
The name suggests a signature like this:
```dart
factory AppTitle.fromTool(Tool tool, {...})
```

2024-02-20 10:21 UTC, d-loose commented on packages/app_center/lib/src/widgets/banner.dart
> +  final double kIconSize;
Please use appropriate types, i.e. `EdgeInsets` for paddigns, `Size` for sizes etc

2024-02-20 10:22 UTC, d-loose commented on packages/app_center/lib/src/widgets/banner.dart
> +  final double kIconSize;
Same as above, please use proper types :)

2024-02-20 10:26 UTC, d-loose commented on packages/app_center/lib/src/widgets/banner.dart
> +            Color.fromARGB(255, 49, 1, 82),
Could we move this to the list of banner colors instead of hardcoding it here?

2024-02-20 10:32 UTC, d-loose commented on packages/app_center/lib/src/widgets/app_card.dart
> +}
This data class is unrelated to the `AppCard` widget and should be moved elsewhere. Also consider using [freezed](https://pub.dev/packages/freezed). The class should at least be immutable and have a `const` constructor.

2024-02-20 10:39 UTC, d-loose commented on packages/app_center/lib/src/widgets/app_card.dart
> +    VoidCallback? onTap,
`onTap` isn't used

2024-02-20 10:41 UTC, d-loose commented on packages/app_center/lib/src/widgets/banner.dart
> +  final double kIconSize;
Types :)

2024-02-20 10:42 UTC, d-loose commented on packages/app_center/lib/src/widgets/banner.dart
> +  final double kIconSize;
Also the `k` naming convention indicates constants, which those are not

2024-02-20 10:42 UTC, d-loose commented on packages/app_center/lib/src/widgets/banner.dart
> +  final double kIconSize;
And don't use the `k`-prefix for non constant symbols

2024-02-20 10:45 UTC, d-loose commented on packages/app_center/lib/src/widgets/snap_grid.dart
> +    required AppLocalizations l10n,
See somewhere above - you shouldn't need to pass the `l10n` argument all the way down, since the localizations can be retrieved from the build context

2024-02-20 10:54 UTC, d-loose commented on packages/app_center/lib/src/search/search_page.dart
> +class InstallAll extends ConsumerWidget {
Could this just be an `ElevatedButton` in a `Center` with appropriate padding?

2024-02-20 11:24 UTC, d-loose commented on packages/app_center/lib/src/search/search_page.dart
> +Future<void> installAll(List<Snap> snaps) async {
As discussed before, this business logic shouldn't be here in the UI, but in a dedicated model. I'd suggest adding a `MultiSnapModel` that takes a snap category as an argument and handles all the communication with the `SnapdService` (similar to what `SnapModel` does for a single snap). You could then create a `multiSnapModelProvider` family and use it in the UI like this:

```dart
...
final model = ref.watch(multiSnapModelProvider(category));
...
ElevatedButton(
  onPressed: model.installAll,
  child: Text(...),
)
...
```
Of course this needs some additional logic for the loading state, similar to the snap model.

The model itself could roughly look like this:
```dart
class MultiSnapModel extends ChangeNotifier {
  MultiSnapModel({
    required this.snapd,
    required this.category,
  }) ...

  Future<void> init() async {
// fetch snaps from snapd (instead of doing this in the search provider)
...
  }

  Future<void> installAll() {
// handle confinement logic and install all the snaps
  }

2024-02-20 11:27 UTC, d-loose commented on packages/app_center/lib/src/snapd/snap_search.dart
> +    );
As mentioned above, I'd move this into its own model, since this isn't really search related anymore.
Maybe it'd be good to completely separate the search page from the category page again as it's quite messy (in a future PR, though).

2024-02-20 11:31 UTC, d-loose commented on packages/app_center/lib/src/store/store_navigator.dart
> +    return pushNamed('/externalTools');
See above

2024-02-20 11:33 UTC, d-loose commented on packages/app_center/test/games_page_test.dart
Awesome :tada:

2024-02-20 11:40 UTC, d-loose requested changes
Great work overall! I've left a few minor comments on general issues regarding conventions and structure. In a lot of places [trailing commas](https://docs.flutter.dev/tools/formatting#using-trailing-commas) would help increase legibility - I didn't leave explicit comments for that.
One thing that still needs a bit of work is the many-snap installation logic. It should really be separated from the UI and moved into a model that interacts with snapd and is made accessible to the UI via a provider family.

2024-02-20 11:53 UTC, d-loose commented on packages/app_center/lib/src/games/games_page_external_tools.dart
> +//TODO: should we localize this stuff?
Forgot to comment here - yes, absolutely! Data like this also shouldn't be stored in the UI code, but moved to a file or database and then be loaded by a view model that provides it to the UI

2024-02-20 12:54 UTC, BLKKKBVSIK commented on packages/app_center/lib/src/games/games_page_external_tools.dart
> +                        Color.fromARGB(255, 29, 27, 112),
We shouldn't have hard-coded colors directly here.

2024-02-20 18:41 UTC, jssotomdz commented on packages/app_center/lib/src/widgets/app_card.dart
> +}
I remember doing this to avoid a circular dependency. Is it better to create a tool.dart that lives in `lib/src/games` and just import it where necessary?

2024-02-20 18:43 UTC, jssotomdz commented on packages/app_center/lib/src/search/search_page.dart
> +class InstallAll extends ConsumerWidget {
I need to get the snaps from the category, which are fetched with the `snapSearchProvider` which in turn requires a `WidgetRef ref`. The way I solved this was wrapping it in a `ConsumerWidget`. Does it make sense? Am I missing something?

2024-02-20 23:15 UTC, jssotomdz commented on packages/app_center/lib/src/search/search_page.dart
> +class InstallAll extends ConsumerWidget {
Got the point, implemented the multiple snaps model and now this isn't needed. Will refactor in next commits

2024-02-22 09:53 UTC, d-loose commented on packages/app_center/lib/src/snapd/snap_search.dart
> +    );
Ah, right I see what you mean now. You'll need to keep it then, as long you're using the search page to display a gaming category with the 'install all' button. In this case it might make sense to simplify the `MultiSnapModel` and directly pass the list of snaps to it instead of fetching them in the  `init()` again. That'd avoid unnecessary requests and also ensure that the snaps that would be installed are actually exactly the same as those shown on the page.
I'll add some more detailed comments on the `MultiSnapModel` later today!

2024-02-22 17:43 UTC, d-loose commented on packages/app_center/lib/src/snapd/snap_search.dart
> +    );
Noticed you're OOO until after the weekend, so I'll comment on the new changes sometime tomorrow - looks very good at first glance!

2024-02-23 16:42 UTC, d-loose commented on packages/app_center/lib/src/games/games_page.dart
> +  static const Size iconSize = Size(32, 32);
`Size.square()` would be clearer here

2024-02-23 16:47 UTC, d-loose commented on packages/app_center/lib/src/games/games_page.dart
> +List<Tool> takeRandom(List<Tool> tools, int num) {
it might be simpler to use `List`'s `shuffle()` and `take()`

2024-02-23 16:53 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +});
This isn't used anywhere (yet). Do you plan to add a progress indicator?

2024-02-23 16:55 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +  late List<Snap> categorySnaps;
```suggestion
  final List<Snap> categorySnaps = [];
```

2024-02-23 16:55 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +    categorySnaps = List.empty(growable: true);
```suggestion
```

2024-02-23 16:59 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +    for (final name in category.featuredSnapNames!) {
It'd be nice to handle the case where a category doesn't have any featured snaps more gracefully here. A simple `assert()` to warn other contributors would be enough for now.

2024-02-23 17:03 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +    for (final name in category.featuredSnapNames!) {
Also, I'm just realizing that we have `getStoreSnaps` for multiple snaps

2024-02-23 17:04 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +  Future<void> install() {
This should probably be called `installAll`

2024-02-23 17:07 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +Future<String> installAll(List<Snap> snaps) async {
This helper method shouldn't be public

2024-02-23 17:08 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +}
Rather than duplicating this, I'd move it to a common file like `snapx.dart`

2024-02-23 17:11 UTC, d-loose commented on packages/app_center/lib/src/snapd/multisnap_model.dart
> +  final snapd = getService<SnapdService>();
Once this is part of the `MultiSnapModel` you can use the model's `snapd` reference

2024-02-23 17:16 UTC, d-loose commented on packages/app_center/lib/src/widgets/app_card.dart
> +}
If it's not intended to be used outside of the 'games' context, I'd move `tool.dart` to `lib/src/games` and export it from `lib/games.dart`.

2024-02-26 13:33 UTC, d-loose commented on packages/app_center/lib/src/games/games_page.dart
> +List<Tool> takeRandom(List<Tool> tools, int num) {
Right, shuffling the list isn't a great idea then. I'd suggest using [`sample()`](https://api.flutter.dev/flutter/package-collection_collection/IterableExtension/sample.html) from [`collection`](https://pub.dev/packages/collection) since we depend on it anyways.

2024-02-26 13:40 UTC, jssotomdz commented on packages/app_center/lib/src/games/games_page.dart
> +List<Tool> takeRandom(List<Tool> tools, int num) {
it has the same problem but now that I think again I could add a `list.where('has logo').sample(3)`. I'll implement it in the next commits

2024-02-27 15:25 UTC, d-loose commented on packages/app_center/test/snap_model_test.dart
> +      final model = MultiSnapModel(snapd: service, category: SnapCategoryEnum.gameDev);
Since we're testing the `MultiSnapModel` here, this belongs in a separate `multi_snap_model_test.dart`.

2024-02-27 15:27 UTC, d-loose commented on packages/app_center/test/test_utils.dart
> +          growable: false)));
Instead of hardcoding this here in the test utils, could we add a corresponding argument to `createMockSnapdService` so that each test can setup the mock according to its needs?

2024-02-27 15:39 UTC, d-loose commented
Do you intend to use the `MultiSnapModel`'s `errorStream` and `activeChangeId` to present errors and installation progress in the UI? If so, please add tests for those :). Otherwise, let's remove those parts to avoid having dead code lying around.

2024-02-27 15:42 UTC, d-loose commented on packages/app_center/test/search_page_test.dart
> +    expect(find.text(tester.l10n.installAll), findsOneWidget);
We could also test whether pressing the 'install all' button calls the corresponding method here

2024-02-28 11:03 UTC, jssotomdz commented on packages/app_center/lib/src/widgets/app_card.dart
> +}
I am reusing the banners, appcards, app title and snap grid widgets to create the tools page and they need access to tool.dart. Games page needs access to these widgets hence creating a circular dependency. Not sure if that's considered outside of games context but these widgets do require the class. Should I proceed with the move anyways?

2024-02-28 11:41 UTC, d-loose approved these changes
Great work! :+1:
Left two small comments. I think in general there's some room for improvement concerning the tests and the UI (e.g. loading states). But I think we could address those things in a future PR :)

2024-02-28 11:41 UTC, d-loose commented on packages/app_center/test/search_page_test.dart
> +    await tester.tap(find.byType(ElevatedButton));
Nitpick: I'd move this further down below your UI assertions, as those test the state of the UI after `pumpAndSettle()`. The only effect of tapping the button is calling `installAll()` - to make that clear, it'd be best to group `tester.tap()` and `verify(..)` together.

2024-02-28 11:41 UTC, d-loose commented on packages/app_center/test/multisnap_model_test.dart
> +  test('install-many', () async {
I think it'd be good to also add a test with mixed classic and strictly confined snap, as this was the case you had issues with.

2024-02-28 12:29 UTC, jssotomdz commented on packages/app_center/test/multisnap_model_test.dart
> +  test('install-many', () async {
this will be addressed in a future pr

2024-03-06 19:58 UTC, jssotomdz approved these changes

2024-03-06 20:01 UTC, merged