Used @freezed to create Rating class
ubuntu/app-center pull request #1669
Opened 2024-05-11 17:47 UTC by j-j-gajjar

2024-05-24 08:08 UTC, spydon approved these changes
Lgtm!

2024-05-24 11:01 UTC, d-loose requested changes

2024-05-24 11:01 UTC, d-loose commented on packages/app_center_ratings_client/lib/src/chart.freezed.dart
> +  $RatingCopyWith<$Res> get rating;
There seems to be an issue with nested `freezed` classes here - this is only part of `ratings.dart` but not `chart.dart`. `Chart` is another `freezed` class, that has a `Rating` field.

I don't know from the top of my head how to fix this, though.

2024-06-26 13:56 UTC, d-loose approved these changes
Code generation really doesn't work well with namespaces and typedefs sometimes.. Thanks for fixing!

2024-06-26 14:06 UTC, merged